# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
<<<<<<< HEAD
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SOCR.xcworkspace -scheme SOCR-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
=======
<<<<<<< HEAD
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SOCR.xcworkspace -scheme SOCR-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
=======
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SandUnPay.xcworkspace -scheme SandUnPay-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
>>>>>>> e6fa452150ade38023b58b59cd97eb126b0b6d7f
>>>>>>> 1058593ebdee0479564806fad772f31545d5f117
- pod lib lint
